Repository ZupIT/horusec-engine, pull requests merged in 2020-11, with the labels that each got.

#13 Bugfix/duplicated findings
  text/unit.go
  text/unit_test.go
Labels: bug

#12 feat(benchmarks): Add more extensive tests and benchmarks for heavy TextUnits
  text/file_test.go
  text/samples/benchmark3.perf
  text/samples/benchmark4.perf
  text/unit_test.go
Labels: documentation

#14 Feature/platform android
  go.mod
  go.sum
  platforms/android/AndroidManifest.2.xml
  platforms/android/AndroidManifest.xml
  platforms/android/manifest.go
  platforms/android/manifest_test.go
  platforms/finding.go
  platforms/rule.go
  rule.go
Labels: enhancement
